"""add uploaded_files table

Revision ID: 22616a328992
Revises: f2f01c221b30
Create Date: 2026-03-25 18:47:18.299754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22616a328992'
down_revision: Union[str, None] = 'f2f01c221b30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_extension', sa.String(length=20), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('upload_status', sa.Enum('uploaded', 'failed', name='uploaded_file_upload_status'), nullable=False),
    sa.Column('validation_status', sa.Enum('pending', 'accepted', 'rejected', name='uploaded_file_validation_status'), nullable=False),
    sa.Column('validation_label', sa.String(length=50), nullable=True),
    sa.Column('validation_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['orchestrator_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploaded_files_session_id'), 'uploaded_files', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uploaded_files_session_id'), table_name='uploaded_files')
    op.drop_table('uploaded_files')
    # ### end Alembic commands ###
