[alembic]
# Ruta a la carpeta alembic
script_location = alembic

# Esto se sobreescribe en env.py con settings.DATABASE_URL,
# pero Alembic igual espera que exista.
sqlalchemy.url = postgresql+psycopg://postgres:postgres@localhost:5432/postgres

# Si usas múltiples versiones, esto es útil
version_locations = alembic/versions

# Opcional: logging más clean
prepend_sys_path = .

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = INFO
handlers = console

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s